movie_name = input("Enter Movie Name -")
viewer_name = input("Enter Viewer Name -")
seat_number = input("Enter Seat Number -")
show_time = input("Enter show time -")

print(F" 🎬 Movie Ticket 🧧 ")
print("Movie Name", movie_name)
print("Viewer Name", viewer_name)
print("Seat Number", seat_number)
print("Show Time", show_time)
print("Enjoy the Show!")